# Generated by Django 5.2.4 on 2025-07-06 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0003_remove_categoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('monofocal', 'Monofocal'), ('bifocal', 'Bifocal'), ('progresivo', 'Progresivo'), ('fotocromatico', 'Fotocromático'), ('antirreflejo', 'Antirreflejo'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_lente_ar', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='categorias.categoria', verbose_name='Categoría')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
