# Generated by Django 5.2.4 on 2025-07-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_lente_ar',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
