# Generated by Django 5.2.4 on 2025-07-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_cover_alter_producto_imagen_lente_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_lente_ar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
